<a href="https://colab.research.google.com/github/prachikushwaha007-ai/Python_for_Data_Science--NPTEL/blob/main/12_Dealing_with_missing_values_NPTEL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import os

In [113]:
import pandas as pd

In [114]:
import numpy as np

In [115]:
df = pd.read_csv('/content/drive/MyDrive/Toyota.csv', index_col=0, na_values=['??','????'])
df.shape

(1436, 10)

In [116]:
# Making copies of df for further operations.

df1 = df.copy()

In [117]:
df2 = df1.copy()

In [118]:
df3 = df1.copy()

In [119]:
# To check null values in pd- isnull() and isna() are used, it gives boolean value.
# How many no. of rows having missing columns.

df.isna().sum()

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [120]:
# To know where the missing value is located.

missing = df2[df2.isnull().any(axis=1)]
missing

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
6,16900,27.0,NaN,Diesel,NaN,NaN,0,2000,3,1245
7,18600,30.0,75889.0,NaN,90.0,1.0,0,2000,3,1245
9,12950,23.0,71138.0,Diesel,NaN,NaN,0,1900,3,1105
15,22000,28.0,18739.0,Petrol,NaN,0.0,0,1800,3,1185
...,...,...,...,...,...,...,...,...,...,...
1428,8450,72.0,NaN,Petrol,86.0,NaN,0,1300,3,1015
1431,7500,NaN,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.0,NaN,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,NaN,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.0,NaN,NaN,86.0,1.0,0,1300,3,1015

In [121]:
# describe() fn. Tto know whether numerical variables should be imputed with mean or median.

df2.describe()

,Price,Age,KM,HP,MetColor,Automatic,CC,Weight
count,1436.000000,1336.000000,1421.000000,1430.000000,1286.000000,1436.000000,1436.000000,1436.00000
mean,10730.824513,55.672156,68647.239972,101.478322,0.674961,0.055710,1566.827994,1072.45961
std,3626.964585,18.589804,37333.023589,14.768255,0.468572,0.229441,187.182436,52.64112
min,4350.000000,1.000000,1.000000,69.000000,0.000000,0.000000,1300.000000,1000.00000
25%,8450.000000,43.000000,43210.000000,90.000000,0.000000,0.000000,1400.000000,1040.00000
50%,9900.000000,60.000000,63634.000000,110.000000,1.000000,0.000000,1600.000000,1070.00000
75%,11950.000000,70.000000,87000.000000,110.000000,1.000000,0.000000,1600.000000,1085.00000
max,32500.000000,80.000000,243000.000000,192.000000,1.000000,1.000000,2000.000000,1615.00000

In [122]:
# since there is no much difference b/w the mean and median, we are going to impure the age variable with the mean value.

df2['Age'].mean()

np.float64(55.67215568862275)

In [123]:
# now we're going to use 55.67 in the missing value, we use fillna() operation.

df2['Age'].fillna(df2['Age'].mean(), inplace=True)
df2

/tmp/ipykernel_1267/2302811564.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Age'].fillna(df2['Age'].mean(), inplace=True)

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.000000,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.000000,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.000000,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.000000,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.000000,38500.0,Diesel,90.0,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,55.672156,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.000000,NaN,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,55.672156,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.000000,NaN,NaN,86.0,1.0,0,1300,3,1015
1435,6950,76.000000,1.0,Petrol,110.0,0.0,0,1600,5,1114

In [124]:
# Missing values of 'KM'.

df2['KM'].median()

63634.0

In [125]:
df2['KM'].fillna(df2['KM'].median(), inplace=True)
df2

/tmp/ipykernel_1267/2967116078.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['KM'].fillna(df2['KM'].median(), inplace=True)

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.000000,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.000000,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.000000,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.000000,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.000000,38500.0,Diesel,90.0,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,55.672156,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.000000,63634.0,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,55.672156,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.000000,63634.0,NaN,86.0,1.0,0,1300,3,1015
1435,6950,76.000000,1.0,Petrol,110.0,0.0,0,1600,5,1114

In [126]:
# Missing values of 'HP'.

df2['HP'].mean()

np.float64(101.47832167832168)

In [127]:
df2['HP'].fillna(df2['HP'].mean(), inplace=True)
df2

/tmp/ipykernel_1267/1364847244.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['HP'].fillna(df2['HP'].mean(), inplace=True)

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.000000,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.000000,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.000000,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.000000,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.000000,38500.0,Diesel,90.0,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,55.672156,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.000000,63634.0,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,55.672156,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.000000,63634.0,NaN,86.0,1.0,0,1300,3,1015
1435,6950,76.000000,1.0,Petrol,110.0,0.0,0,1600,5,1114

In [128]:
# To check missing value after filling values.

df2.isnull().sum()

Price          0
Age            0
KM             0
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [129]:
# series.value_counts() returns a series containing counts of missing values,
# The values will be in descending order so that 1st element is the most frequently-occurring element.
# Excludes NA values by default.

df2['FuelType'].value_counts()

FuelType
Petrol    1177
Diesel     144
CNG         15
Name: count, dtype: int64

In [130]:
# To get the model value of FuelType for filling values.

df2['FuelType'].value_counts().index[0]

'Petrol'

In [131]:
df2['FuelType'].fillna(df2['FuelType'].value_counts().index[0])

0       Diesel
1       Diesel
2       Diesel
3       Diesel
4       Diesel
         ...
1431    Petrol
1432    Petrol
1433    Petrol
1434    Petrol
1435    Petrol
Name: FuelType, Length: 1436, dtype: object

In [132]:
# To get the mode value of Metcolor.

df2['MetColor'].mode()

0    1.0
Name: MetColor, dtype: float64

In [133]:
# To fill the mode in Metcolor with indexing.

df2['MetColor'].fillna(df2['MetColor'].mode()[0])
df2

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.000000,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.000000,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.000000,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.000000,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.000000,38500.0,Diesel,90.0,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,55.672156,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.000000,63634.0,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,55.672156,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.000000,63634.0,NaN,86.0,1.0,0,1300,3,1015
1435,6950,76.000000,1.0,Petrol,110.0,0.0,0,1600,5,1114

In [134]:
# To check the missing value in df.

df2.isnull().sum()

Price          0
Age            0
KM             0
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [135]:
# Imputing Missing Values Using lambda functions.
# To fill the NA/NaN values in both numerical and categorical variables at one stretch.
# applying on third copy of df.

def impute_values(x):
  if x.dtype == 'float' or x.dtype == 'int':
    return x.fillna(x.mean())
  else:
    return x.fillna(x.mode()[0])
df3 = df3.apply(impute_values)
df3

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.000000,46986.000000,Diesel,90.0,1.000000,0,2000,three,1165
1,13750,23.000000,72937.000000,Diesel,90.0,1.000000,0,2000,3,1165
2,13950,24.000000,41711.000000,Diesel,90.0,0.674961,0,2000,3,1165
3,14950,26.000000,48000.000000,Diesel,90.0,0.000000,0,2000,3,1165
4,13750,30.000000,38500.000000,Diesel,90.0,0.000000,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,55.672156,20544.000000,Petrol,86.0,1.000000,0,1300,3,1025
1432,10845,72.000000,68647.239972,Petrol,86.0,0.000000,0,1300,3,1015
1433,8500,55.672156,17016.000000,Petrol,86.0,0.000000,0,1300,3,1015
1434,7250,70.000000,68647.239972,Petrol,86.0,1.000000,0,1300,3,1015
1435,6950,76.000000,1.000000,Petrol,110.0,0.000000,0,1600,5,1114

In [136]:
# To check the missing values.

df3.isnull().sum()

Price        0
Age          0
KM           0
FuelType     0
HP           0
MetColor     0
Automatic    0
CC           0
Doors        0
Weight       0
dtype: int64