<a href="https://colab.research.google.com/github/prachikushwaha007-ai/Python_for_Data_Science--NPTEL/blob/main/9_Exploratory_data_analysis_NPTEL_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = '/content/drive/MyDrive/Toyota.csv'

In [ ]:
df = pd.read_csv

In [ ]:
df

<function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'>

In [ ]:
# changing directory.
import os

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Toyota.csv', index_col=0, na_values=["??","???"])
df

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90,1.0,0,2000,three,1165
1,13750,23.0,72937.0,Diesel,90,1.0,0,2000,3,1165
2,13950,24.0,41711.0,Diesel,90,NaN,0,2000,3,1165
3,14950,26.0,48000.0,Diesel,90,0.0,0,2000,3,1165
4,13750,30.0,38500.0,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,NaN,20544.0,Petrol,86,1.0,0,1300,3,1025
1432,10845,72.0,NaN,Petrol,86,0.0,0,1300,3,1015
1433,8500,NaN,17016.0,Petrol,86,0.0,0,1300,3,1015
1434,7250,70.0,NaN,NaN,86,1.0,0,1300,3,1015
1435,6950,76.0,1.0,Petrol,110,0.0,0,1600,5,1114

In [ ]:
df1 = df.copy()  # to make an copy of df for analysis.
df1

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90,1.0,0,2000,three,1165
1,13750,23.0,72937.0,Diesel,90,1.0,0,2000,3,1165
2,13950,24.0,41711.0,Diesel,90,NaN,0,2000,3,1165
3,14950,26.0,48000.0,Diesel,90,0.0,0,2000,3,1165
4,13750,30.0,38500.0,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,NaN,20544.0,Petrol,86,1.0,0,1300,3,1025
1432,10845,72.0,NaN,Petrol,86,0.0,0,1300,3,1015
1433,8500,NaN,17016.0,Petrol,86,0.0,0,1300,3,1015
1434,7250,70.0,NaN,NaN,86,1.0,0,1300,3,1015
1435,6950,76.0,1.0,Petrol,110,0.0,0,1600,5,1114

In [ ]:
# pandas.crosstab() to compute a frequency table of the factors.
pd.crosstab(index=df1['FuelType'], columns='count', dropna=True)

col_0     count
FuelType
CNG          15
Diesel      144
Petrol     1177

In [ ]:
# two way table - pandas.crosstab()
pd.crosstab(index = df1['Automatic'], columns = df1['FuelType'], dropna=True)

FuelType   CNG  Diesel  Petrol
Automatic
0           15     144    1104
1            0       0      73

In [ ]:
# Two-way table-joint probability, we use normalize = True for no. to proportion.
pd.crosstab(index = df1['Automatic'], columns = df1['FuelType'], normalize = True, dropna=True)

FuelType        CNG    Diesel    Petrol
Automatic
0          0.011228  0.107784  0.826347
1          0.000000  0.000000  0.054641

In [ ]:
# two - way table- marginal probability use margins = True.
pd.crosstab(index = df1['Automatic'], columns = df1['FuelType'], margins = True, normalize = True, dropna=True)

FuelType        CNG    Diesel    Petrol       All
Automatic
0          0.011228  0.107784  0.826347  0.945359
1          0.000000  0.000000  0.054641  0.054641
All        0.011228  0.107784  0.880988  1.000000

In [ ]:
# conditional probability.
pd.crosstab(index = df1['Automatic'], columns = df1['FuelType'], normalize = 'index', dropna=True)

FuelType        CNG    Diesel    Petrol
Automatic
0          0.011876  0.114014  0.874109
1          0.000000  0.000000  1.000000

In [ ]:
pd.crosstab(index = df1['Automatic'], columns = df1['FuelType'], normalize = 'columns', dropna=True)

FuelType   CNG  Diesel    Petrol
Automatic
0          1.0     1.0  0.937978
1          0.0     0.0  0.062022

In [ ]:
# coorelation to compute pairwise correlatin of col. excluding NA/values
# df.corr(self, method='pearson')
numerical_data = df1.select_dtypes(include=['number'])
print(numerical_data.shape)

(1436, 7)

In [ ]:
# correlation matrix
corr_matrix = numerical_data.corr()
corr_matrix

,Price,Age,KM,MetColor,Automatic,CC,Weight
Price,1.000000,-0.878407,-0.574720,0.112041,0.033081,0.165067,0.581198
Age,-0.878407,1.000000,0.512735,-0.099659,0.032573,-0.120706,-0.464299
KM,-0.574720,0.512735,1.000000,-0.093825,-0.081248,0.299993,-0.026271
MetColor,0.112041,-0.099659,-0.093825,1.000000,-0.013973,0.029189,0.057142
Automatic,0.033081,0.032573,-0.081248,-0.013973,1.000000,-0.069321,0.057249
CC,0.165067,-0.120706,0.299993,0.029189,-0.069321,1.000000,0.651450
Weight,0.581198,-0.464299,-0.026271,0.057142,0.057249,0.651450,1.000000